apiVersion: v1
kind: Secret
metadata:
  name: users-secret
  namespace: fcg-users
  labels:
    app: users
type: Opaque
stringData:
  USERS_DB_CONNECTION_STRING: $(USERS_DB_CONNECTION_STRING)
  JWT_ISSUER: $(JWT_ISSUER)
  JWT_AUDIENCE: $(JWT_AUDIENCE)
  JWT_KEY: $(JWT_KEY)